# Generated by Django 4.1 on 2022-08-08 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elmodel',
            name='duedate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elmodel',
            name='priority',
            field=models.CharField(choices=[('danger', 'high'), ('info', 'middle'), ('success', 'low')], default='danger', max_length=50),
            preserve_default=False,
        ),
    ]
