# Generated by Django 4.1 on 2022-09-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elapp', '0003_newword'),
    ]

    operations = [
        migrations.AddField(
            model_name='newword',
            name='mean',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
