# Generated by Django 4.1 on 2022-09-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elapp', '0005_newword_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='newword',
            name='useful',
            field=models.PositiveIntegerField(default='0', verbose_name='the number of access'),
        ),
    ]
